# Generated by Django 5.2.1 on 2025-05-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cyberpoints",
            field=models.IntegerField(default=0),
        ),
    ]
