# Generated by Django 5.2.1 on 2025-05-31 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_profile_cyberpoints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScamReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("element_text", models.TextField(blank=True)),
                ("element_html", models.TextField(blank=True)),
                ("reason", models.TextField()),
                ("ai_analysis", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("scam_type", models.CharField(blank=True, max_length=100)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("false_positive", "False Positive"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("points_earned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_blocked_by_reporter", models.BooleanField(default=True)),
                ("last_visited", models.DateTimeField(blank=True, null=True)),
                ("visit_attempts_after_report", models.IntegerField(default=0)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scam_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reported_by", "-created_at"],
                        name="webapp_scam_reporte_a62fe7_idx",
                    ),
                    models.Index(
                        fields=["url", "reported_by"], name="webapp_scam_url_7092ef_idx"
                    ),
                ],
            },
        ),
    ]
